### ISSUE TITLE
Azure AD B2C giving AADB2C90117 error...

### ISSUE THREAD

**Issue by PtwHub** [cradle77/Blazor.Msal#11]
This isn't really an issue but more of a migration request: to AAD B2C, or  what needs to be changed in the appsetting.json is not yet clear. There have been several changes in AAD B2C lately. I'm used to the classic OpenID flow, and I am not understanding how this works yet -- or is different -- with MSAL. Why is the redirect back to the client even when I supply the /signin-oids of the api server? Any tips welcome, else I'll keep reading.

appsettings.json blazor API server:
  "AllowedHosts": "*",
    "AzureAdB2C": {
        "ClientId": "59caf4a9-84f5-49b5-bd51-331a3er08bf3",
        "RedirectUri": "https://localhost:44397/signin-oidc",
        "ClientSecret": "9tzGL98fS/2p:LA]YfzuHj.?9Jp_p[ND",
        "Tenant": "yyyyyDevTest.onmicrosoft.com",
        "SignUpSignInPolicyId": "B2C_1_HubSignInV2Policy",
        "ResetPasswordPolicyId": "B2C_1_V2SSPR",
        "EditProfilePolicyId": "B2C_1_V2SiPe"
    }

appsettings.json client:
{
    "Authority": "https://login.microsoftonline.com/tfp/yyyyDevTest.onmicrosoft.com/B2C_1_HubSignInV2Policy/v2.0",
    "ClientId": "59caf4a9-84f5-49b5-bd51-331a3er08bf3"
}

Gives me this error in the WASM Browser Console:
AADB2C90117: The scope 'app://blazor.msal.api/api.access' provided in the request is not supported

**Comment by cradle77** [comment]
Hello,

I guess you are using the example project. `MainLayout.razor` sets a scope for the login which apparently is not in the App Registration you have created in B2C.

Working with Azure AD B2C might require a couple of tweaks, I'm currently on it and will publish a tutorial as soon as it's done.

**Comment by PtwHub** [comment]
OK, I wrongly assumed that those scope requirements were coming from AAD B2C. I'll see what happens now... Let me know if you see any problems in my appsettings. Thanks

PS: this needs to be added to your AzureAdB2C appsettings too

        "Instance": "https://login.microsoftonline.com",

, but then I just get one step futher, not done yet and get WASM error that Des.Blazor.Authorization.Msal.MsalAuthenticationStateProvider is Null.

**Comment by cradle77** [comment]
Alright, had a quick look and I have to add some changes to the library. 

2 main issues:
- a parameter in the MSAL config which I don’t support at the moment 
- the different token that B2C issues compared to normal Azure AD

**Comment by PtwHub** [comment]
OK, all good, I'll keep trying to understand the whole MSAL flow vis-a-vis std OpeinId-Connect (newness in B2C here) and await further infos. Once the sample runs, it will be easier to understand the flow. What is the MSAL advantage ... looks like a lot of code!?

I noticed that Blazor.Msal.Client.ClientConfig is not used anywhere, so apparently neither are the settings in the client's appsettings.json.

**Comment by nootn** [comment]
Hi, I started looking at this as I require it.  I am documenting the steps I am taking below which might help implement this...

I added:
`validateAuthority = false`
to line 37 of Msal.cs, obviously that should be:
`validateAuthority = config.ValidateAuthority`
..and also added to the config class etc.  But I am just trying to figure out how to quickly get it working.

After I do that, it let's me actually authenticate, but when it comes back to the Blazor app I get:
`WASM: ﻿Unhandled exception rendering component: blazor.webassembly.js:1:35618
WASM: System.NullReferenceException: Object reference not set to an instance of an object. blazor.webassembly.js:1:35618
WASM:   at Des.Blazor.Authorization.Msal.MsalAuthenticationStateProvider.<SignInAsync>b__4_0 () <0x242c2e8 + 0x000f0> in <0835b507a99546918b699671122f38c0>:0 blazor.webassembly.js:1:35618`

I found that `this.GetAuthenticationStateAsync()).User.Identity.Name` was getting a null reference exception.
The fix was to make sure "Display Name" was chosen as an application scope as per [this stack overflow article](https://stackoverflow.com/a/50815062)
That seemed to set the name, but the underlying userName is still not set, so anywhere that checks if the identity is authenticated fails.

As I said I need to keep moving quickly so this is not a fix, but it just so happens if you can set the "userName" property in the return value of "AzureAd.prototype.getAccount" (in blazor.azuread.js) then it works.  So this is a super dodgy implementation but demonstrates it working - we do get an "accountIdentifier" returned from Msal - so I just set the userName to that:
`

    AzureAd.prototype.getAccount = function () {
        var acc = this.msalObj.getAccount();
        // Dodgy fix below!
        if (acc && acc.accountIdentifier && !acc.userName){
            acc.userName = acc.accountIdentifier;
        }
        return acc;
    };

`

Hopefully that helps!  If I get time to circle back I will try to a pull request with a proper fix but don't have time right now sorry!

**Comment by cradle77** [comment]
Hello, 

thanks very much for the info :) I had already started implementing the support to B2C, but then I paused it waiting for a more stable release of Blazor WebAssembly.

I plan to push a new version to GitHub within the next week.

**Comment by horros** [comment]
Any updates on this? I too got this working using a similar workaround to @nootn, but using ```acc.userName = acc.name``` instead.

**Comment by cradle77** [comment]
Hello guys, the new Blazor 3.2.0 preview 2 adds support for token based authentication
https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/

Therefore I think there's very little point in updating this project :) 

Thanks a lot for having used it!
