### ISSUE TITLE
Is there a way to cache the accesstoken?

### ISSUE THREAD

**Issue by sowsan** [cradle77/Blazor.Msal#18]
Howz the access token life cycle with this implementation works?

**Comment by cradle77** [comment]
Hi,

It’s all managed by MSAL.js.L, which caches the token on local storage. 

All you have to do is making sure you try to acquire an access token via my API each time you need to make an HTTP request. 

The system will retrieve it from the cache if available, or try to automatically renew it if expired. 

The renewal will happen silently if possible, otherwise will prompt the user for authentication.

**Comment by cradle77** [comment]
Hello! The new Blazor 3.2.0 preview 2 adds support for token based authentication
https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/

Therefore I think there's very little point in updating this project :)

Thanks a lot for having used it!
